package com.miaoshaproject.miaosha.dao;

import com.miaoshaproject.miaosha.dataobject.UserDO;
import org.springframework.stereotype.Service;

@Service("userDOMapper")
public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Oct 29 16:05:24 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Oct 29 16:05:24 CST 2019
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Oct 29 16:05:24 CST 2019
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Oct 29 16:05:24 CST 2019
     */
    UserDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Oct 29 16:05:24 CST 2019
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Oct 29 16:05:24 CST 2019
     */
    int updateByPrimaryKey(UserDO record);

    /**
     * 通过手机号获取用户信息
     * @param telephone
     * @return
     */
    UserDO selectByTelephone(String telephone);
}